---
- name: Встановлення та налаштування сервера Apache з додатком та сервера MariaDB
  hosts: server, db
  become: yes
  vars:
    db_host: "{{ db_host }}"
    db_name: "{{ db_name }}"
    db_user: "{{ db_user }}"
    db_pass: "{{ db_pass }}"

  tasks:
    - name: Оновлення кешу apt та перевірка актуальності пакунків
      apt:
        update_cache: yes
        upgrade: dist

    - name: Встановлення сервера Apache
      apt:
        name: apache2
        state: present

    - name: Встановлення PHP та необхідних модулів для Laravel
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-mbstring
        - php-xml
        - php-curl
        - composer

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Laravel application from GitHub
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ app_dir }}"
        update: no  # Avoid unnecessary updates if already cloned (optional)
      vars:
        git_repo_url: "https://github.com/Practical-DevOps/app-for-devops"
        app_dir:  /var/www/app-for-devops 

    - name: Install laravel dependencies
      composer:
        command: install
        working_dir: /var/www/app-for-devops
      become: yes

  - name: Copy .env file 
    copy:
      src: /var/www/app-for-devops/.env.example
      dest: /var/www/app-for-devops/.env  
      owner: root 
      group: root  
      mode: 0644  

    - name: Встановлення сервера MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Налаштування бази даних MariaDB
      mysql_db:
        name: "{{ db_name }}"
        state: present
      become_user: root
      become: yes

    - name: Створення користувача MariaDB
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
      become_user: root
      become: yes

  handlers:
    - name: перезапуск apache
      service:
        name: apache2
        state: restarted
